title: Moleculer - Progressive microservices framework for Node.js
subtitle: "Progressive microservices framework for Node.js"
description: "Moleculer is a progressive microservices framework powered by Node.js"
author: MoleculerJS
language: en
timezone: UTC
url: https://moleculer.services
github_edit_link: https://github.com/moleculerjs/site/edit/master/source/
root: /
permalink: news/:year/:month/:day/:title/
#archive_dir: news
code_dir: downloads/code
#new_post_name: :year-:month-:day-:title.md # File name of new posts
#post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: moleculer
# Markdown
## https://github.com/chjj/marked
markdown:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

#deploy:
#  type: git
#  repo: git@github.com:moleculerjs/moleculerjs.github.io.git

# disqus_shortname: moleculer
google_analytics: UA-99099811-1
# fb_admins: 100000247608790
algolia:
  en:
    api_key: xyz
    index_name: moleculer_web

twitter: MoleculerJS
github: moleculerjs/moleculer
stackoverflow: questions/tagged/moleculer

alias:
  docs/benchmark.html: docs/0.14/benchmark.html
  docs/broker.html: docs/0.14/broker.html
  docs/cachers.html: docs/0.14/cachers.html
  docs/circuit-breaker.html: docs/0.14/circuit-breaker.html
  docs/context.html: docs/0.14/context.html
  docs/contributing.html: docs/0.14/contributing.html
  docs/docker.html: docs/0.14/docker.html
  docs/errors.html: docs/0.14/errors.html
  docs/examples.html: docs/0.14/examples.html
  docs/faq.html: docs/0.14/faq.html
  docs/logger.html: docs/0.14/logger.html
  docs/metrics.html: docs/0.14/metrics.html
  docs/modules.html: docs/0.14/modules.html
  docs/moleculer-cli.html: docs/0.14/moleculer-cli.html
  docs/moleculer-repl.html: docs/0.14/moleculer-repl.html
  docs/moleculer-web.html: docs/0.14/moleculer-web.html
  docs/nodes.html: docs/0.14/nodes.html
  docs/runner.html: docs/0.14/runner.html
  docs/serializers.html: docs/0.14/serializers.html
  docs/serverless.html: docs/0.14/serverless.html
  docs/service-registry.html: docs/0.14/service-registry.html
  docs/service.html: docs/0.14/service.html
  docs/statistics.html: docs/0.14/statistics.html
  docs/support.html: support.html
  docs/transporters.html: docs/0.14/transporters.html
  docs/usage.html: docs/0.14/usage.html
  docs/validation.html: docs/0.14/validation.html

  0.14/docs/support.html: support.html
  0.14/docs/modules.html: modules.html

  0.14/docs/benchmark.html: docs/0.14/benchmark.html
  0.14/docs/broker.html: docs/0.14/broker.html
  0.14/docs/cachers.html: docs/0.14/cachers.html
  0.14/docs/circuit-breaker.html: docs/0.14/circuit-breaker.html
  0.14/docs/context.html: docs/0.14/context.html
  0.14/docs/contributing.html: docs/0.14/contributing.html
  0.14/docs/docker.html: docs/0.14/docker.html
  0.14/docs/errors.html: docs/0.14/errors.html
  0.14/docs/examples.html: docs/0.14/examples.html
  0.14/docs/faq.html: docs/0.14/faq.html
  0.14/docs/logger.html: docs/0.14/logger.html
  0.14/docs/metrics.html: docs/0.14/metrics.html
  0.14/docs/moleculer-cli.html: docs/0.14/moleculer-cli.html
  0.14/docs/moleculer-repl.html: docs/0.14/moleculer-repl.html
  0.14/docs/moleculer-web.html: docs/0.14/moleculer-web.html
  0.14/docs/nodes.html: docs/0.14/nodes.html
  0.14/docs/runner.html: docs/0.14/runner.html
  0.14/docs/serializers.html: docs/0.14/serializers.html
  0.14/docs/serverless.html: docs/0.14/serverless.html
  0.14/docs/service-registry.html: docs/0.14/service-registry.html
  0.14/docs/service.html: docs/0.14/service.html
  0.14/docs/statistics.html: docs/0.14/statistics.html
  0.14/docs/transporters.html: docs/0.14/transporters.html
  0.14/docs/usage.html: docs/0.14/usage.html
  0.14/docs/validation.html: docs/0.14/validation.html

  api/context.html: api/0.14/context.html
  api/protocol.html: api/0.14/protocol.html
  api/service-broker.html: api/0.14/service-broker.html
  api/service.html: api/0.14/service.html

  docs/index.html: docs/0.14/index.html
  api/index.html: docs/0.14/index.html
